config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  get "home/about" => "homes#about"
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum:50}
  validates :name, uniqueness: true

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
 def after_sign_up_path_for(resource)
   user_path(resource)
 end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
 def after_sign_in_path_for(resource)
   user_path(resource)
 end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
 
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    
    if current_user.nil?
    redirect_to user_session_path
    end
   
    @user = current_user
    @users = User.all
    @book = Book.new
  end
  
  def show
    
    if current_user.nil?
    redirect_to user_session_path
    end
  
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end
  
  def edit
    
    @user = User.find(params[:id])
    if current_user.nil?
      redirect_to user_session_path
      
    elsif @user != current_user
     redirect_to user_path(current_user)
     
    end
    
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
    flash[:success] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
      render  :edit
    end
    
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def book_params 
    params.permit(:title, :body, :user_id) 
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side_bar.html.erb
<div class="container px-5 px-sm-0 errors_message">

     <% if @user.errors.any? %>
        <div class="error_explanation">
        <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <% @user.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
          <% end %>
        </div>
      <% end %>

      <% if @book.errors.any? %>
        <div class="error_explanation">
        <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <ul>
              <li><%= message %></li>
            </ul>
          <% end %>
        </div>
      <% end %>
</div>

<div class="col-md-3">

  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size:"100x100" %>
  <table class="table">
    <tbody><tr></tr>
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
    </tbody>
  </table>

  <div class="row">
    <% if user.id == current_user.id %>
    <%= link_to "", edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user＿ ' %>
    <% else %>
    <%= link_to "", edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user＿ ' %>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local:true do |f| %>
  <div class="form-group book_title">
    <%= f.label :title %><br />
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %><br />
    <%= f.text_area :body, class:"form-control book_body"  %>
  </div>
  <%= f.submit 'Create Book', class:"btn btn-success" %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

    <% if @user.errors.any? %>
      <div class="error_explanation">
      <h3><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
        <% @user.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
        <% end %>
      </div>
    <% end %>

    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, class: "form-control name", id:"user_name"%>
      </div>

      <div class="form-group">
        <%= f.label :image %><br />
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>

     <div class="form-group">
        <%= f.label :introduction %><br />
        <%= f.text_area :introduction, class: "form-control introduction", id:"user_introduction" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/side_bar', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th class="col-3">image</th>
            <th class="col-6">name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tbody>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x40' %></td>

              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">

  <%= render 'users/side_bar', book: @book, user: @user %>

  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>

  	<table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <% @books.each do |book| %>
      <tbody>
        <tr>
          <td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:"40x40" %><% end %></td>
          <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
          <td><%= book.body %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
  </div>
</div>