config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  get "home/about" => "homes#about"
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    
    if current_user.nil?
    redirect_to user_session_path
    end
    
    @user = current_user
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    
    if @book.save
      
    if current_user.nil?
    redirect_to user_session_path
    end
    
      flash[:success] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render "books/index"
    end
    
  end
  
  
  def show
    
    if current_user.nil?
    redirect_to user_session_path
    end
    
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end
  
  def edit
    
   @book = Book.find(params[:id])
    
   if current_user.nil?
     redirect_to user_session_path
     
   elsif @book.user != current_user
     redirect_to books_path
     
   end
    
  end
  
  def update
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      
      render :edit
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params 
    params.require(:book).permit(:title, :body) 
  end
 
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
		<h1>Editing Book</h1>

		<% if @book.errors.any? %>
      <div class="error_explanation">
      <h3><%= @book.errors.count %> error prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
        <ul>
          <li><%= message %></li>
        </ul>
        <% end %>
      </div>
    <% end %>

  	<%= form_with model:@book, local:true do |f| %>
    <div class="form-group">
      <%= f.label :title %><br />
      <%= f.text_field :title, autofocus: true, class: "form-control", id:"book_title"%>
    </div>

   <div class="form-group">
      <%= f.label :body %><br />
      <%= f.text_area :body, class: "form-control", id:"book_body" %>
    </div>

    <div class="form-group">
      <%= f.submit "Update Book", class: "btn btn-success" %>
    </div>
    <% end %>
    <%= link_to "Show", book_path(@book) %>
    <span>|</span>
		<%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/side_bar', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th class="col-1"></th>
            <th >Title</th>
            <th >Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= link_to user_path(book.user_id) do %><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:"40x40" %><% end %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="row">
  <%= render 'users/side_bar', book: @book_new, user: @user %>

  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
    	<tbody>
    	  <tr>
          <td>
            <%= link_to user_path(@user.id) do %><%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size:"40x40" %><% end %><br>
            <%= link_to @user.name, user_path(@user.id) %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if @user.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger", method: :delete,"data-confirm"=>"本当に消しますか？" %></td>
          <% end %>
         </tr>
       </tbody>
    </table>
  </div>
</div>